name: Docker action
description: An action utilizing docker image
inputs:
  who-to-greet:
    description: Who to greet?
    required: true
    default: 'World'
outputs:
  answer: # id of output
  description: 'The answer is always 42'
runs:
  using: docker
  image: answer.dockerfile
  args:
    - ${{ inputs.who-to-greet }}