name: "Hello from JS"
on:
  pull_request:
    branches: [ main ]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    env:
      GREETING_PATH: .github/workflows/actions/greeting
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        name: 'Prepare npm'
        with:
          node-version: 20
      - run: npm install ${GREETING_PATH}
      - name: 'hello-action'
        uses: ./.github/workflows/actions/greeting
      - name: 'finishing'
        run: echo "good bye"
