name: First manual workflow
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username'
        required: true
      reason:
        description: 'Why are you running this workflow?'
        required: true
        default: 'I want to run it now!'
jobs:
  test_manual_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo "User ${{ github.event.inputs.username}} ran a workflow manually."
          echo "Reason: ${{ github.event.inputs.reason}}"
  another_action:
    needs: [test_manual_workflow]
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo "Running another step for ${{ github.events.inputs.username}}"