name: Label PR
on:
  pull_request:
    types: [ opened, reopened ]
jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5